name: read_stats
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.1.5
  csv : ^6.0.0
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  flex_color_picker: ^3.7.1
  stylish_bottom_bar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icon/readstats.png"