name: Build iOS

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS (Release)
        run: flutter build ios --release --no-codesign

      - name: Create Folder
        run: |
          pwd
          cd build/ios/iphoneos/
          pwd
          mkdir -p Payload
          mv Runner.app Payload/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Payload
          path: build/ios/iphoneos/